holamundo/holamundo/urls.py
from django.contrib import admin
from django.urls import path, include

from rescate_perros.views import *

urlpatterns = [

    
    path('import_excel/', import_excel_view, name='import_excel'),
    path('accounts/', include('allauth.urls')),


    path('admin/', admin.site.urls),
    path('hola/', holamundo, name='holamundo'),
    path('', home, name='home'),
    path('', home, name='dashboard'),
    path('lista_perros/ciudad/<str:ciudad>/', lista_perros, name='lista_perros'),
    path('perro/<int:codigo_perro>/', ver_perro, name='detalle_perro'),
    path('perro_api/<int:codigo_perro>/', ver_perro_api, name='detalle_perro_api'),
    
    # URLS de REFUGIOS
    path('refugio/', lista_refugios, name='lista_refugios'),
    path('refugio/<int:codigo_refugio>/', ver_refugio, name='ver_refugio'),
    path('refugio/nuevo/', nuevo_refugio, name='nuevo_refugio'),
    path('refugio/editar/<int:codigo_refugio>/', editar_refugio, name='editar_refugio'),
    path('refugio/eliminar/<int:codigo_refugio>/', eliminar_refugio, name='eliminar_refugio'),

    # Extra_Pages
    path("extra_pages/", include("extra_pages.urls")),
    # layouts
    path("layouts/", include("layouts.urls")),  

    # Productos
    path('products/', product_list, name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),


 



]

holamundo/layouts/urls.py
from django.urls import path
from layouts import views

urlpatterns = [
    # Vertical Layout
    path('light-Sidebar',views.LightSidebarView.as_view(),name='layouts-light_sidebar'),
    path('compact-Sidebar',views.CompactSidebarView.as_view(),name='layouts-compact_sidebar'),
    path('icon-Sidebar',views.IconSidebarView.as_view(),name='layouts-icon_sidebar'),
    path('boxed-width',views.BoxLayoutView.as_view(),name='layouts-boxed-width'),
    path('colored-Sidebar',views.ColoredSidebarView.as_view(),name='layouts-colored_sidebar'),

    #Horizontal Layout
    path('horizontal',views.HorizontalView.as_view(),name='layouts-horizontal'),
    path('horizontal-topbar-light',views.TopbarLightHoriView.as_view(),name='layouts-hori_topbar_light'),
    path('horizontal-boxed-width',views.BoxedWidthHoriView.as_view(),name='layouts-hori_boxed_width'),
    

]    

holamundo/rescate_perros/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from django.urls import reverse
from django.contrib.auth.models import User


class Postulante(models.Model):
    user = models.OneToOneField(User, related_name='postulante', on_delete=models.CASCADE)
    department = models.CharField(max_length=100)

class Personal(models.Model):
    user = models.OneToOneField(User, related_name='personal', on_delete=models.CASCADE)
    department = models.CharField(max_length=100)


TIPO_REFUGIO_CHOICES = [
    ('C', 'Campestre'),
    ('U', 'Urbano'),
]

class Refugio(models.Model):
    nombre = models.CharField(max_length=144, 
                              blank=False, 
                              null=False, 
                              verbose_name='Nombre del refugio',
                              help_text='El nombre comercial del refugio o el nombre corto')
    direccion = models.CharField(max_length=144, blank=True)
    tipo = models.CharField(max_length=5, blank=True, choices=TIPO_REFUGIO_CHOICES)
    descripcion = models.TextField(blank=True, null=True)
    ciudad = models.CharField(max_length=144, blank=False, null=False, default='Quito')
    fecha_actualizacion = models.DateTimeField(
        default=timezone.now, 
        verbose_name='fecha de actualización',
        help_text='Fecha de la última actualización del registro.'
    )
    es_activo = models.BooleanField(blank=False, 
                                    null=False, 
                                    default=True, 
                                    verbose_name='¿Propiedad activa?')
    
    documento = models.FileField(
        upload_to="documentos/", 
        blank=True, 
        verbose_name='documentos del refugio',
        help_text='Documento del refugio'
    )

    def __str__(self) -> str:
        return f'{self.pk} - {self.nombre}'
    
    def get_absolute_url(self):
        return reverse('ver_refugio', kwargs={'codigo_refugio': self.id})
    
    def get_edit_url(self):
        return reverse('editar_refugio', kwargs={'codigo_refugio': self.id})
    
    def get_delete_url(self):
        return reverse('eliminar_refugio', kwargs={'codigo_refugio': self.id})
    
    def cantidad_perros(self):
        return self.perros.count()


SEXO_CHOICES = [
    ('M', 'Macho'),
    ('F', 'Hembra'),
]

ESTERILIZADO_CHOICES = [
    (True, 'Sí'),
    (False, 'No'),
]

class Perro(models.Model):
    nombre = models.CharField(
        max_length=144, 
        blank=False, 
        null=False, 
        verbose_name='nombre',
        help_text='Nombre completo del perro.'
    )
    descripcion = models.TextField(
        blank=True, 
        null=True, 
        verbose_name='descripción',
        help_text='Descripción detallada del perro.'
    )
    sexo = models.CharField(
        max_length=1, 
        blank=False, 
        null=False, 
        choices=SEXO_CHOICES, 
        verbose_name='sexo',
        help_text='Sexo del perro.'
    )
    esterilizado = models.BooleanField(
        default=False, 
        choices=ESTERILIZADO_CHOICES, 
        verbose_name='esterilizado',
        help_text='Indica si el perro está esterilizado.'
    )
    ficha_perro = models.FileField(
        upload_to="uploads/", 
        blank=True, 
        verbose_name='ficha del perro',
        help_text='Ficha médica del perro.'
    )
    fecha_nacimiento = models.DateField(
        blank=True, 
        null=True, 
        verbose_name='fecha de nacimiento',
        help_text='Fecha de nacimiento del perro.'
    )
    fecha_actualizacion = models.DateTimeField(
        default=timezone.now, 
        verbose_name='fecha de actualización',
        help_text='Fecha de la última actualización del registro.'
    )
    
    refugio_actual = models.ForeignKey(
        'Refugio', 
        related_name='perros', 
        on_delete=models.SET_NULL, 
        null=True, 
        verbose_name='refugio actual',
        help_text='Refugio en el que se encuentra actualmente el perro.'
    )
    foto = models.ImageField(
        upload_to="media/", 
        blank=True, 
        null=True, 
        verbose_name='foto',
        help_text='Foto del perro.',

    )

    class Meta:
        verbose_name = 'perro'
        verbose_name_plural = 'perros'
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

    def calcular_edad(self):
        """Calcula la edad del perro a partir de su fecha de nacimiento."""
        if self.fecha_nacimiento:
            hoy = date.today()
            return hoy.year - self.fecha_nacimiento.year - ((hoy.month, hoy.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day))
        else:
            return 'Desconocida'  # Devuelve un string en lugar de None para una mejor representación

    @property
    def edad(self):
        """Propiedad para obtener la edad calculada del perro."""
        return self.calcular_edad()
    
    

class AtencionesClinica(models.Model):
    perro = models.ForeignKey(Perro, on_delete=models.CASCADE)
    fecha_atencion = models.DateField()
    peso = models.FloatField()
    talla = models.FloatField()
    resumen = models.TextField()
    veterinario = models.CharField(max_length=100)

    def __str__(self):
        return f"Atención {self.fecha_atencion} para {self.perro.nombre}"

VACUNAS_CHOICES = [
    ('DHPP', 'Distemper, Hepatitis, Parainfluenza and Parvovirus'),
    ('RABIES', 'Rabies'),
    ('LEPTO', 'Leptospirosis'),
    ('BORDETELLA', 'Bordetella Bronchiseptica'),
    ('LYME', 'Lyme Disease'),
    ('GIARDIA', 'Giardia'),
    ('CORONA', 'Coronavirus'),
    ('HEARTWORM', 'Heartworm Prevention'),
    ('INFLUENZA', 'Canine Influenza'),
    ('PARVO', 'Parvovirus'),
    ('ADENO', 'Adenovirus'),
    ('DISTEMPER', 'Canine Distemper'),
    ('HEPATITIS', 'Infectious Canine Hepatitis'),
]

class Vacuna(models.Model):
    fecha_vacunacion = models.DateField()
    vacuna = models.CharField(max_length=100, choices=VACUNAS_CHOICES)
    certificado = models.CharField(max_length=100)
    perro = models.ForeignKey(Perro, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.vacuna} para {self.perro.nombre}"

class Persona(models.Model):
    nombre = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)
    correo = models.EmailField()
    intereses = models.TextField()
    rol = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class InteresadosEnRescatar(models.Model):
    perro = models.ForeignKey(Perro, on_delete=models.CASCADE)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.persona.nombre} interesado en {self.perro.nombre}"



######
# SUPERSTORE
    
class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    state = models.CharField(max_length=100)
    postal_code = models.IntegerField()

    class Meta:
        unique_together = ('name', 'country', 'state', 'postal_code')

    def __str__(self):
        return f"{self.name}, {self.state}, {self.country.name}"

class Category(models.Model):
    name = models.CharField(max_length=100)
    sub_category = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} - {self.sub_category}"

class Product(models.Model):
    product_id = models.CharField(max_length=20)
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Order(models.Model):
    order_id = models.CharField(max_length=20)
    order_date = models.DateField()
    ship_date = models.DateField()
    ship_mode = models.CharField(max_length=50)
    customer_id = models.CharField(max_length=20)
    customer_name = models.CharField(max_length=100)
    segment = models.CharField(max_length=50)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    region = models.CharField(max_length=50)

    def __str__(self):
        return self.order_id
    
class OrderLine(models.Model):
    order = models.ForeignKey(Order, related_name='order_lines', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    sales = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    discount = models.DecimalField(max_digits=5, decimal_places=2)
    profit = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.order.order_id} - {self.product.name}"

holamundo/templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        
    </head>

    <body>
    {% block content %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>

</html>

holamundo/templates/base_old.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        
    </head>

    <body>
    {% block content %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>

</html>

holamundo/templates/dashboard.html
{% extends 'partials/base.html' %}
{% load static %}
{% block extra_css %}
    <link href="{% static 'libs/chartist/dist/chartist.min.css' %}" rel="stylesheet">
{% endblock  %}

{% block content %}


{% endblock %}
{% block extra_javascript %}

    <!-- Peity chart-->
    <script src="{% static 'libs/peity/jquery.peity.min.js' %}"></script>

    <!-- Plugin Js-->
    <script src="{% static 'libs/chartist/dist/chartist.min.js' %}"></script>
    <script src="{% static 'libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js' %}"></script>

    <script src="{% static 'js/pages/dashboard.init.js' %}"></script>

{% endblock %}

holamundo/templates/formulario_refugio.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="container mt-3">
        <h1>Nuevo {{titulo}}</h1>
                <form method="post" enctype="multipart/form-data">
                        
                        {% csrf_token %}

                        {% for field in form %}

                        <div class="form-group">
                                <label for="exampleInputEmail1">{{ field.label_tag }}</label>
                                 
                                {{ field | add_class:"form-control"  }}
                        </div>

                        {% endfor %}
                        <div class="form-group"></div>
                        <input type="submit" class="mt-10 btn btn-primary" value="Submit">
                        </div>
                </form>
</div>
                
                

        
{% endblock %}

holamundo/templates/index.html
{% extends 'partials/base.html' %} 
{% load static %} 

{% block extra_css %} 
{% endblock %} 

{% block body %} 
{% endblock %} 

{% block content %} 

        <h1> {{titulo}}  </h1>
        <p> {{mensaje}} </p>
        <p> 
            <p>¿tiene_postulante? {{tiene_postulante}}</p>
            <p>tiene_personal? {{tiene_personal}}</p>
            <p>ID_POSTULANTE? {{request.user.postulante.pk}}</p>
            <p>ID_PERSONAL? {{request.user.personal.pk}}</p>
            <p>ID_USER? {{request.user.pk}}</p>
        
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Raza</th>
                <th scope="col">Edad</th>
                </tr>
            </thead>
            <tbody>
        {% for p in perros %}
            <tr>
                <td>
                    {% if p.nombre == "Rex" %}🐕{% endif %}
                    {{p.nombre}}
                </td>
                <td>{{p.raza}}</td>
                <td>{{p.edad}} años</td>
            </tr>
        {% endfor %}
    </tbody>
        </p>
        <p>Contar palabras
        {{contar_frecuencia_palabras}}
    </p>

    <h2>{{texto_traducido}}</h2>

    
{% endblock %} 
{% block extra_javascript %} 
{% endblock %}

holamundo/templates/lista_perros.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
        <h1>Perros en {{ ciudad }}</h1>
        <ul class="list-group">
            {% for perro in perros %}
            <li class="list-group-item">
                <a href="/perro/{{ perro.pk }}">{{ perro.nombre }}</a> - Refugio: {{ perro.refugio_actual.nombre }}
                <!-- Añade más detalles que desees mostrar -->
            </li>
            {% empty %}
            <li class="list-group-item">No hay perros registrados en esta ciudad.</li>
            {% endfor %}
        </ul>
</div>
        
{% endblock %}

holamundo/templates/lista_productos.html
{% extends 'partials/base.html' %} 
{% load static %} 

{% block extra_css %} 
{% endblock %} 

{% block body %} 
{% endblock %} 

{% block content %} 

<div class="container mt-3">
    <h2>Lista de Productos</h2>
    <div class="row">
        {% for product in products %}
            <div class="col-md-6 mb-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">Categoría: {{ product.category.name }}</p>
                        <!-- Asegúrate de ajustar la URL según tu archivo urls.py -->
                        <a href="{% url 'product_detail' product.id %}" class="btn btn-primary">Ver Detalles</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a href="?page=1" class="btn btn-outline-info">&laquo; primera</a>
                <a href="?page={{ products.previous_page_number }}" class="btn btn-outline-info">anterior</a>
            {% endif %}
            
            <span class="current">
                Página {{ products.number }} de {{ products.paginator.num_pages }}.
            </span>
            
            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}" class="btn btn-outline-info">siguiente</a>
                <a href="?page={{ products.paginator.num_pages }}" class="btn btn-outline-info">última &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %} 
{% block extra_javascript %} 
{% endblock %}

holamundo/templates/lista_refugios.html
{% extends 'partials/base.html' %} 
{% load static %} 

{% block extra_css %} 
{% endblock %} 

{% block body %} 
{% endblock %} 

{% block content %} 

<div class="container mt-4">
    <p>{{color}}</p>
    <h1>Refugios</h1>
    <ul class="list-group">
        {% for r in refugios %}
        <li class="list-group-item">
            <a href="{{r.get_absolute_url}}">{{ r.nombre }}</a> 
            {{ r.cantidad_perros }} perros
        </li>
        {% empty %}
        <li class="list-group-item">No hay refugios.</li>
        {% endfor %}
    </ul>
</div>

{% endblock %} 
{% block extra_javascript %} 
{% endblock %}

holamundo/templates/perros.html
{% extends 'base.html' %}


{% block content %}
        <h1> {{titulo}} </h1>
        <p> {{mensaje}} </p>
        <h2> {{comida}}</h2>
{% endblock %}

holamundo/templates/product_detail_view.html
{% extends 'partials/base.html' %} 
{% load static %} 

{% block extra_css %} 
{% endblock %} 

{% block body %} 
{% endblock %} 

{% block content %} 

<div class="container mt-4">
    <h1>Detalle del Producto</h1>
    <div class="card">
        <div class="card-header">
            Producto: {{ product.name }}
        </div>
        <div class="card-body">
            <h5 class="card-title">Categoría: {{ product.category.name }}</h5>
            <!-- Suponiendo que existe un campo 'description' en tu modelo de Product -->
            <p class="card-text">Descripción: {{ product.description }}</p>
            <!-- Más detalles del producto como precio, etc. -->
            <p class="card-text">Precio: ${{ product.price }}</p>
            <p class="card-text">Cantidad disponible: {{ product.quantity }}</p>
            
            <!-- Añade aquí más campos según sea necesario -->

            <a href="{% url 'product_list' %}" class="btn btn-primary">Volver a la lista de productos</a>
        </div>
    </div>
</div>

{% endblock %} 
{% block extra_javascript %} 
{% endblock %}

holamundo/templates/refugio.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="container mt-4">
        <div class="card">
                <div class="card-header">
                        <h5 class="card-title">Refugio: {{ refugio.nombre }}</h5>
                </div>
             
                <p class="card-text">{{ refugio.descripcion }}</p>
                <p class="card-text"><strong>Direccion:</strong> {{ refugio.direccion }}</p>
                <p class="card-text"><strong>Ciudad:</strong> {{ refugio.ciudad }}</p>
                <p class="card-text"><strong>Actualización:</strong> {{ refugio.fecha_actualizacion }}</p>
                <p class="card-text"><strong>Tipo refugio:</strong> {{ refugio.tipo }}</p>

           
                
                <a type="button" href="{{ refugio.get_delete_url }}" class="btn btn-danger">Eliminar</a>
                <a type="button" href="{{ refugio.get_edit_url }}" class="btn btn-warning">Editar</a>

</div>
</div>
        
{% endblock %}

holamundo/templates/ver_perro.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
        <div class="card">
                <div class="card-header">

                        <h5 class="card-title">{{ perro.nombre }}</h5>
        
                </div>
                {% if perro.foto %}
                <img src="{{ perro.foto.url }}" class="card-img-top mb-3" alt="{{ perro.nombre }}" style="max-height: 400px; object-fit: cover;">
                {% endif %}
                <p class="card-text">{{ perro.descripcion }}</p>
                <p class="card-text"><strong>Sexo:</strong> {{ perro.get_sexo_display }}</p>
                <p class="card-text"><strong>Esterilizado:</strong> {{ perro.get_esterilizado_display }}</p>
                <p class="card-text"><strong>Fecha de Nacimiento:</strong> {{ perro.fecha_nacimiento|date:"d/m/Y" }}</p>
                <p class="card-text"><strong>Edad:</strong> {{ perro.edad }}</p>
                <p class="card-text"><strong>Refugio Actual:</strong> </p>


</div>
</div>
        
{% endblock %}